// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khscimofyjkuicwpkstl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtoc2NpbW9meWprdWljd3Brc3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDU1NzAsImV4cCI6MjA3MTcyMTU3MH0.U0vA7--OYmoWLlP_LhlMZxJzxAuQbi4-Qo0VSwZ2AaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});